# Generated by Django 3.1b1 on 2020-07-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
